# Generated by Django 4.2.24 on 2025-09-16 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Relationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우 중인 사용자들",
            ),
        ),
    ]
