# Generated by Django 4.2.24 on 2025-09-23 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("approvals", "0001_initial"),
        ("approvals", "0002_alter_approval_status"),
        (
            "approvals",
            "0003_alter_approval_processed_at_alter_approval_status_and_more",
        ),
        ("approvals", "0004_alter_approval_options"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                ("submitted_at", models.DateTimeField(verbose_name="신청날짜")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리날짜"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="신청 내역")),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
            ],
        ),
    ]
