# Generated by Django 4.2.24 on 2025-09-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commend",
            new_name="Comment",
        ),
    ]
