# Generated by Django 4.2.24 on 2025-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_commend_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="post", verbose_name="썸네일 이미지"
            ),
        ),
    ]
